use antonio_1;
CREATE TABLE POST(
Num INT PRIMARY KEY AUTO_INCREMENT,
Author INT NOT NULL,
Creation DATETIME NOT NULL,
Content TEXT NOT NULL,
CONSTRAINT fk_post_user2 FOREIGN KEY(Author) REFERENCES user2(num)
);

/*multiline*/
-- single line

CREATE TABLE POST_LIKED(
user2 INT NOT NULL,
Post INT NOT NULL,
PRIMARY KEY(user2,Post),
CONSTRAINT fk_post_liked_user2 FOREIGN KEY(user2) REFERENCES user2(num),
CONSTRAINT fk_post_liked_post FOREIGN KEY(POST) REFERENCES POST(num)
);